sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build -t personal-website .

script:
  - docker run -v $(pwd)/public:/app/public personal-website

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./public
  target_branch: gh-pages
  on:
    branch: master